use_frameworks!

target 'BDTestsUI_Example' do
    pod 'BDTests'
  pod 'BDTestsUI', :git => 'https://github.com/bytedissident/BDTestsUI'

  target 'BDTestsUI_Tests' do
    inherit! :search_paths

    
  end
end
