# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BDTestsUITests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BDTestsUITests
  pod 'BDTests', :git => 'https://github.com/bytedissident/BDTests'
  pod 'Alamofire'

  target 'BDTestsUITestsUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'BDTests', :git => 'https://github.com/bytedissident/BDTests'

  end

end
